[package]
name = "bufrw"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"

[dev-dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }

[[bench]]
name = "benches"
harness = false